services:
  unifi-network-armv8-a:
    container_name: farfoxachedocker.unifi-network-armv8-a
    image: unifi-network-armv8-a:latest
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    volumes:
      - var-lib-unifi:/var/lib/unifi
      - usr-lib-unifi:/usr/lib/unifi
    network_mode: host
    devices:
      - /dev/log:/dev/log
    restart: on-failure

volumes:
  var-lib-unifi:
  usr-lib-unifi:
